#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in8,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  touch,          sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           LEDrive,       tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,            ,             tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           fork,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           L_lift,        tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port6,           R_lift,        tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port7,           REDrive,       tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port8,           claw,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           clawArm,       tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_5)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*		NOTE:
Things marked with //FIX are things that are probably dependant on external
factors and need to change depending. Just make sure they're all right before
testing or stuff.
*/



//   __        __   __                          __          __        ___  __
//  / _` |    /  \ |__)  /\  |       \  /  /\  |__) |  /\  |__) |    |__  /__`
//  \__> |___ \__/ |__) /~~\ |___     \/  /~~\ |  \ | /~~\ |__) |___ |___ .__/
//

float kP_drive = 2; //2
float kP_drift = 10; //10
float kD = 16; //15.6
float kI = 0.36; //0.36
float toMotor = 0;
float powerP = 0;
float powerI = 0;
float powerD = 0;

float headingAngle = 0;
int setTime = 0;

//Conversions
float inches_per_tile = 24; //23.25, 22.25
float ticks_per_revolution = 392; //FIX This is for the high speed configuration only
float ticks_per_inch = ticks_per_revolution/(PI*4); //FIX 4" omni wheels
float ticks_per_tile = ticks_per_inch*inches_per_tile;

//moveStraight variables
float error;
float power;
float driftPower;
float targetTicks;
float prevError;
float gyroError;
float derivative;
float integral = 0;
float integral_active_zone = 40; //FIX idk man arbitrary, 130
float errorThreshold = 2; //errorThresholdInTicks=(ticks_per_inch)*(errorThresholdInInches) arbitrary

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"



//   __   __   ___              ___  __
//  |__) |__) |__      /\  |  |  |  /  \ |\ |
//  |    |  \ |___    /~~\ \__/  |  \__/ | \|
//

void pre_auton()
{
	slaveMotor(R_lift, L_lift);
	SensorType[gyro] = sensorNone;
	wait1Msec(1000);
	SensorType[gyro] = sensorGyro;
	wait1Msec(2000);
	SensorValue[gyro] = 0;
	headingAngle = SensorValue[gyro]/10;
}



//    __       ___          __      ___  ___
//   /__` |   |__  |  |    |__)  /\  |  |__
//   .__/ |__ |___ |/\|    |  \ /~~\ |  |___
//

int motorSlewRate = 5; //20
float tempMotor = 0;
float motorReq[2];


void assignPower (int motorIndex, int motorReq_Index){ //REDrive is index 6, LEDrive is index 1
	tempMotor = motor[motorIndex];
	if (tempMotor != motorReq[motorReq_Index])
	{
		if (tempMotor < motorReq[motorReq_Index])
		{
			tempMotor = tempMotor +	motorSlewRate;
			if (tempMotor > motorReq[motorReq_Index])
			{
				tempMotor = motorReq[motorReq_Index];
			}
		}
		else
		{
			tempMotor = tempMotor -	motorSlewRate;
			if (tempMotor < motorReq[motorReq_Index])
			{
				tempMotor = motorReq[motorReq_Index];
			}
		}

		motor[motorIndex] = tempMotor;
	}
}

task slewRate()
{
	while (1)
	{
		assignPower(6, 1); //REDrive is index 6
		assignPower(1, 0); //LEDrive is index 1
		wait1Msec(15);
	}
}


//         __        ___     __  ___  __          __       ___
//   |\/| /  \ \  / |__     /__`  |  |__)  /\  | / _` |__|  |
//   |  | \__/  \/  |___    .__/  |  |  \ /~~\ | \__> |  |  |
//

//if robot is not straight by the end of loop, it will become the new heanding angle
//gyro did not take into account when the sensor value overflow
void moveStraight(int direction, float tiles){
	targetTicks = tiles*ticks_per_tile;

	if (tiles == 1){
		setTime = 2000;
		kP_drive = 2;
		kD = 15.7;
		kI = 0.36; //0.36
		if (direction == 1 || direction == 2){
			targetTicks = tiles*(ticks_per_tile - 65);
		}
		if (direction == -1){
			targetTicks = tiles*(ticks_per_tile - 85;
		}
	}

	if (tiles == 2){
		setTime = 3000;
		kP_drive = 2; //2
		kD = 15.7; //16
		kI = 0.36; //0.8
		if (direction == 1){
			targetTicks = tiles*(ticks_per_tile - 65); //50
		}
		if (direction == -1){
			targetTicks = tiles*(ticks_per_tile - 85); //45
		}
	}
	prevError = targetTicks;
	nMotorEncoder[LEDrive]=0;
	nMotorEncoder[REDrive]=0;
	error = targetTicks-((abs(nMotorEncoder[LEDrive])+abs(nMotorEncoder[REDrive]))/2);
	float scaling = 127/targetTicks;
	integral = 0;
	clearTimer(T1);
	while((time1[T1]<setTime)){ // && (error>errorThreshold)1500
		error = targetTicks-((abs(nMotorEncoder[LEDrive])+abs(nMotorEncoder[REDrive]))/2);
		gyroError = (SensorValue[gyro]/10)-headingAngle; //Error in degrees

		integral = integral + error;
		if(abs(error)>integral_active_zone){
			integral = 0;
		}
		if (abs(error) <= errorThreshold){
			integral = 0;
		}

		derivative = error - prevError;

		driftPower = gyroError * kP_drift;
		powerP = kP_drive*error*direction*scaling;
		powerI = kI*integral*direction*scaling;
		powerD = kD*derivative*direction*scaling;
		power = (powerP)+(powerI)+(powerD);

		if (power > 97){
			power = 97;
		}
		else if (power < -97){
			power = -97;
		}

		if (driftPower > 30){
			driftPower = 30;
		}
		else if (driftPower < -30){
			driftPower = -30;
		}

		if(abs(error)<30){
			driftPower = 0;
		}

		toMotor = power;
		motorReq[0] = toMotor + driftPower; //left
		motorReq[1] = toMotor - driftPower; //right
		prevError = error;
		wait1Msec(25);
	}
	toMotor = 0;
	motorReq[0] = toMotor;
	motorReq[1] = toMotor;
}


//   __       ___            __   __
//  |  \  /\   |   /\  |    /  \ / _`
//  |__/ /~~\  |  /~~\ |___ \__/ \__>
//

task datalog(){
	while(1){
		datalogDataGroupStart();
		datalogAddValue( 0, error);
		datalogAddValue( 1, gyroError);
		datalogAddValue( 2, driftPower);
		datalogAddValue( 3, toMotor);
		datalogAddValue( 4, powerP);
		datalogAddValue( 5, powerI);
		datalogAddValue( 6, powerD);
		datalogAddValue( 7, tempMotor);
		datalogDataGroupEnd();
		wait1Msec(25);
	}
}

//            ___  __
//   /\  |  |  |  /  \
//  /~~\ \__/  |  \__/
//

task autonomous()
{
	startTask(slewRate);
	startTask(datalog);
	moveStraight(1,1);
	wait1Msec(500);
	moveStraight(1,1);
	wait1Msec(500);
	moveStraight(-1,1);
	wait1Msec(500);
	moveStraight(-1,1);
	wait1Msec(500);
	moveStraight(1,2);
	wait1Msec(500);
	moveStraight(-1,2);
	wait1Msec(500);
	moveStraight(1,1);
	wait1Msec(500);
	moveStraight(-1,1);
	wait1Msec(500);
	stopTask(slewRate);
	stopTask(datalog);
}



//        __   ___  __      __   __       ___  __   __
//  |  | /__` |__  |__)    /  ` /  \ |\ |  |  |__) /  \ |
//  \__/ .__/ |___ |  \    \__, \__/ | \|  |  |  \ \__/ |___
//

task usercontrol()
{
	int driveThreshold = 20;
	while (true){
		if(abs(vexRT[Ch3])>driveThreshold){
			motor[LEDrive] = vexRT[Ch3];
		}	else {
			motor[LEDrive] = 0;
		}
		if(abs(vexRT[Ch2])>driveThreshold){
			motor[REDrive] = vexRT[Ch2];
		}	else {
			motor[REDrive] = 0;
		}
		motor[clawArm] = (vexRT[Btn6UXmtr2]-vexRT[Btn5UXmtr2])*127;
		motor[claw] = vexRT[Btn7DXmtr2]*127;
		motor[fork] = (vexRT[Btn6U]-vexRT[Btn6D])*127;
		motor[L_lift] = (vexRT[Btn8RXmtr2]-vexRT[Btn8DXmtr2])*127;
	}
}
